<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Slideshow\Form\SlideshowCategory'                       => __DIR__ . '/src/Slideshow/Form/SlideshowCategory.php',
    'Slideshow\Form\SlideshowImage'                          => __DIR__ . '/src/Slideshow/Form/SlideshowImage.php',
    'Slideshow\Form\SlideshowCategoryFilter'                 => __DIR__ . '/src/Slideshow/Form/SlideshowCategoryFilter.php',
    'Slideshow\Event\SlideshowEvent'                         => __DIR__ . '/src/Slideshow/Event/SlideshowEvent.php',
    'Slideshow\Service\Slideshow'                            => __DIR__ . '/src/Slideshow/Service/Slideshow.php',
    'Slideshow\Model\SlideshowBase'                          => __DIR__ . '/src/Slideshow/Model/SlideshowBase.php',
    'Slideshow\Model\SlideshowWidget'                        => __DIR__ . '/src/Slideshow/Model/SlideshowWidget.php',
    'Slideshow\Model\SlideshowAdministration'                => __DIR__ . '/src/Slideshow/Model/SlideshowAdministration.php',
    'Slideshow\Controller\SlideshowAdministrationController' => __DIR__ . '/src/Slideshow/Controller/SlideshowAdministrationController.php',
    'Slideshow\Exception\SlideshowException'                 => __DIR__ . '/src/Slideshow/Exception/SlideshowException.php',
    'Slideshow\View\Widget\SlideshowWidget'                  => __DIR__ . '/src/Slideshow/View/Widget/SlideshowWidget.php',
    'Slideshow\View\Helper\SlideshowImageUrl'                => __DIR__ . '/src/Slideshow/View/Helper/SlideshowImageUrl.php',
    'Slideshow\Module'                                       => __DIR__ . '/Module.php',
    'Slideshow\Test\SlideshowBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
];
