<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Slideshow') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
    <h1>
        <img src="<?php  echo $this->layoutAsset('icon/slideshow.png', 'image', 'slideshow') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
        <?php echo $this->escapeHtml($this->pageTitle) ?>
    </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
    $this->baseTabs = [
        'list_categories' => [
            'name' => $this->translate('List of categories'),
            'controller' => 'slideshow-administration',
            'action' => 'list-categories',
            'check_acl' => true
        ]
    ]
?>