<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Add a category') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of categories')) ?>

<!-- render a header -->
<?php echo $this->render('slideshow/slideshow-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-categories' // selected action is the "list categories"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of categories'),
            'controller' => 'slideshow-administration',
            'action' => 'list-categories',
            'check_acl' => true
        ],
        'add_category' => [
            'name' => $this->subPageTitle,
            'controller' => 'slideshow-administration',
            'action' => 'add-category',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('General info'),
    'body' => $this->partial('partial/form', ['form' => $this->category_form])
]) ?>