<?php $this->declareVars('content', 'extraActions', 'subPageTitle', 'parentPageTitle', 'currentPageTitle') ?>

<?php $this->parentPageTitle = $this->translate('List of categories') ?>
<?php $this->subPageTitle = $this->translate('Browse images') ?>
<?php $this->currentPageTitle = $this->translate('Add an image') ?>

<?php $this->headTitle($this->currentPageTitle) ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->category['name']) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('slideshow/slideshow-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-categories' // selected action is the "list-categories"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'slideshow-administration',
            'action' => 'list-categories',
            'check_acl' => true
        ],
        'browse_images' => [
            'name' => $this->category['name'] . ' - ' . $this->subPageTitle,
            'controller' => 'slideshow-administration',
            'action' => 'browse-images',
            'params' => [
                'slug' => $this->category['id'],
            ],
            'check_acl' => true
        ],
        'add_image' => [
            'name' => $this->currentPageTitle,
            'controller' => 'slideshow-administration',
            'action' => 'add-image',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'slideshow-administration',
        'action' => 'edit-category',
      'params' => [
         'slug' => $this->category['id']
      ],
        'name' => $this->translate('Edit the category'),
        'check_acl' => true
    ],
   [
        'controller' => 'slideshow-administration',
        'action' => 'delete-categories',
        'name' => $this->translate('Delete the category'),
        'check_acl' => true,
        'confirm' => $this->translate('Category will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'categories' : [{$this->category['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'slideshow-administration', 'action' => 'list-categories'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'slideshow-administration',
        'action' => 'add-category',
        'name' => $this->translate('Add a category'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('New image'),
                'body' => $this->partial('partial/form', ['form' => $this->image_form]),
                'notification' => false
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('New image'),
                'body' => $this->partial('partial/form', ['form' => $this->image_form]),
                'notification' => false
            ]) ?>
        </div>
    <?php endif ?>
</div>