<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of categories') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('slideshow/slideshow-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-categories' // selected action is the "list categories"
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'slideshow-administration',
    'action' => 'list-categories',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Category name'),
            'order_name' => 'name'
        ],
        [
            'title' => $this->translate('Images'),
            'order_name' => 'images'
        ]
    ],
    'paginator' => $this->paginator,
    'helpers' => [
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
            [
                'name' => $this->translate('Add a category'),
                'controller' => 'slideshow-administration',
                'action' => 'add-category',
                'check_acl' => true
            ]
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'slideshow-administration',
                'action' => 'delete-categories',
                'check_acl' => true,
                'confirm' => $this->translate('Selected slideshow categories will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
            [
                'name' => $this->translate('Edit the category'),
                'controller' => 'slideshow-administration',
                'action' => 'edit-category',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ],
            [
                'name' => $this->translate('Browse images'),
                'controller' => 'slideshow-administration',
                'action' => 'browse-images',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/browse_action.png', 'image', 'slideshow')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'slideshow-categories',
        'multiple_actions' => [
            'items_name' => 'categories[]'
        ]
    ],
    'actions_extra_check' => [
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Slideshow categories'),
    'body' => $this->content
]) ?>